[phi-3_5-vision-instruct-onnx]
    [phi-3_5-vision-instruct-onnx.metadata]
        owned_by    = 'Microsoft'
        permission  = []
        description = 'Phi-3.5 Vision is a lightweight, state-of-the-art open multimodal model built upon datasets that include synthetic data and filtered publicly available web data with a focus on very high-quality, reasoning dense data both on text and vision. The model belongs to the Phi-3.5 model family, and the multimodal version supports up to 128K context length (in tokens). The base model has undergone a rigorous enhancement process, incorporating both supervised fine-tuning and direct preference optimization, to ensure precise instruction adherence and robust safety measures.'
    [phi-3_5-vision-instruct-onnx.network]
        type = 'gRPC'
        url = 'app:50051'